// Generated by CoffeeScript 1.6.3
(function() {
  var check;

  check = require('check-types');

  module.exports = {
    Array: function(v) {
      return check.array(v);
    },
    Date: function(v) {
      return check.date(v);
    },
    Error: function(v) {
      return v instanceof Error;
    },
    Buffer: function(v) {
      return v instanceof Buffer;
    },
    boolean: function(v) {
      return 'boolean' === typeof v;
    },
    number: function(v) {
      return check.number(v);
    },
    string: function(v) {
      return check.string(v);
    },
    "function": function(v) {
      return check.fn(v);
    },
    undefined: function(v) {
      return 'undefined' === typeof v;
    },
    "null": function(v) {
      return v === null;
    },
    object: function(v) {
      return check.object(v);
    },
    symbol: function(v) {
      return 'symbol' === typeof v;
    },
    url: function(v) {
      return check.webUrl(v);
    }
  };

}).call(this);
