// Generated by CoffeeScript 1.6.3
(function() {
  var check;

  check = require('check-types');

  module.exports = {
    Array: function(v) {
      return Array.isArray(v);
    },
    Date: function(v) {
      return v instanceof Date;
    },
    Error: function(v) {
      return v instanceof Error;
    },
    Buffer: function(v) {
      return v instanceof Buffer;
    },
    boolean: function(v) {
      return 'boolean' === typeof v;
    },
    number: function(v) {
      return 'number' === typeof v;
    },
    string: function(v) {
      return 'string' === typeof v;
    },
    "function": function(v) {
      return 'function' === typeof v;
    },
    undefined: function(v) {
      return 'undefined' === typeof v;
    },
    "null": function(v) {
      return v === null;
    },
    object: function(v) {
      return 'object' === typeof v && v !== null;
    },
    symbol: function(v) {
      return 'symbol' === typeof v;
    }
  };

}).call(this);
