// Generated by CoffeeScript 1.6.3
(function() {
  var Hash,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  Hash = (function() {
    Hash.RESERVED_KEY_NAMES = ['setKeys', 'reset', 'remove', 'getData', 'keys'];

    function Hash(keys, comparator) {
      var _this = this;
      if (keys == null) {
        keys = [];
      }
      if (typeof comparator !== 'function') {
        throw new TypeError('Invalid comparator');
      }
      this._store = {};
      this.setKeys(keys);
      this._comparator = comparator;
      Object.defineProperty(this, 'length', {
        get: function() {
          return Object.keys(_this._store).length;
        }
      });
    }

    Hash.prototype.setKeys = function(keys) {
      var _this = this;
      if (!Array.isArray(keys)) {
        throw new TypeError('keys must be type array');
      }
      return keys.forEach(function(key) {
        if (typeof key !== 'string') {
          throw new TypeError('Invalid key');
        }
        if (__indexOf.call(Hash.RESERVED_KEY_NAMES, key) >= 0) {
          throw new TypeError("`" + key + "` is already defined");
        }
        return Object.defineProperty(Hash.prototype, key, {
          get: function() {
            return _this._store[key] || null;
          },
          set: function(value) {
            if (!_this._comparator(value)) {
              throw new TypeError('Invalid type of member');
            }
            return _this._store[key] = value;
          },
          enumerable: true,
          configurable: true
        });
      });
    };

    Hash.prototype.reset = function() {
      return this._store = {};
    };

    Hash.prototype.remove = function(key) {
      var value;
      if (!(typeof key === 'string') || key === '') {
        throw new TypeError('Invalid key');
      }
      if (this._store[key] == null) {
        return false;
      }
      value = this._store[key];
      this._store[key] = void 0;
      return value;
    };

    Hash.prototype.getData = function() {
      return this._store;
    };

    Hash.prototype.keys = function() {
      return Object.keys(this._store);
    };

    return Hash;

  })();

  module.exports = Hash;

}).call(this);
